# Generated by Django 3.1.6 on 2021-02-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='teampics')),
                ('role', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=150)),
                ('insta', models.CharField(max_length=150)),
            ],
        ),
    ]
